package xxsg.oracle.apps.ont.store.model.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 04 10:26:05 CEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ResponsibilitiesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserId,
        ResponsibilityId,
        ApplicationId,
        ResponsibilityName,
        Description;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int RESPONSIBILITYID = AttributesEnum.ResponsibilityId.index();
    public static final int APPLICATIONID = AttributesEnum.ApplicationId.index();
    public static final int RESPONSIBILITYNAME = AttributesEnum.ResponsibilityName.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ResponsibilitiesVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public BigDecimal getUserId() {
        return (BigDecimal) getAttributeInternal(USERID);
    }

    /**
     * Gets the attribute value for the calculated attribute ResponsibilityId.
     * @return the ResponsibilityId
     */
    public BigDecimal getResponsibilityId() {
        return (BigDecimal) getAttributeInternal(RESPONSIBILITYID);
    }

    /**
     * Gets the attribute value for the calculated attribute ApplicationId.
     * @return the ApplicationId
     */
    public BigDecimal getApplicationId() {
        return (BigDecimal) getAttributeInternal(APPLICATIONID);
    }

    /**
     * Gets the attribute value for the calculated attribute ResponsibilityName.
     * @return the ResponsibilityName
     */
    public String getResponsibilityName() {
        return (String) getAttributeInternal(RESPONSIBILITYNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }
}

