package xxsg.oracle.apps.ont.store.model.vo;

import java.math.BigDecimal;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 04 10:26:05 CEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ResponsibilitiesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ResponsibilitiesVOImpl() {
    }

    /**
     * Returns the bind variable value for p_user_id.
     * @return bind variable value for p_user_id
     */
    public BigDecimal getp_user_id() {
        return (BigDecimal) getNamedWhereClauseParam("p_user_id");
    }

    /**
     * Sets <code>value</code> for bind variable p_user_id.
     * @param value value to bind as p_user_id
     */
    public void setp_user_id(BigDecimal value) {
        setNamedWhereClauseParam("p_user_id", value);
    }
}

