package xxsg.oracle.apps.ont.store.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 04 11:23:13 CEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SessionInfoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SessionInfoVOImpl() {
    }
}

