package xxsg.oracle.apps.ont.store.model.lov;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 04 17:41:16 CEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LanguagesLovVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        LanguageCode,
        Description,
        NlsLanguage,
        NlsTerritory,
        IsoLanguage,
        IsoTerritory;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LANGUAGECODE = AttributesEnum.LanguageCode.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int NLSLANGUAGE = AttributesEnum.NlsLanguage.index();
    public static final int NLSTERRITORY = AttributesEnum.NlsTerritory.index();
    public static final int ISOLANGUAGE = AttributesEnum.IsoLanguage.index();
    public static final int ISOTERRITORY = AttributesEnum.IsoTerritory.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LanguagesLovVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute LanguageCode.
     * @return the LanguageCode
     */
    public String getLanguageCode() {
        return (String) getAttributeInternal(LANGUAGECODE);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Gets the attribute value for the calculated attribute NlsLanguage.
     * @return the NlsLanguage
     */
    public String getNlsLanguage() {
        return (String) getAttributeInternal(NLSLANGUAGE);
    }

    /**
     * Gets the attribute value for the calculated attribute NlsTerritory.
     * @return the NlsTerritory
     */
    public String getNlsTerritory() {
        return (String) getAttributeInternal(NLSTERRITORY);
    }

    /**
     * Gets the attribute value for the calculated attribute IsoLanguage.
     * @return the IsoLanguage
     */
    public String getIsoLanguage() {
        return (String) getAttributeInternal(ISOLANGUAGE);
    }

    /**
     * Gets the attribute value for the calculated attribute IsoTerritory.
     * @return the IsoTerritory
     */
    public String getIsoTerritory() {
        return (String) getAttributeInternal(ISOTERRITORY);
    }
}

