package xxsg.oracle.apps.ont.store.model.modules.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 05 12:31:57 CEST 2015
// ---------------------------------------------------------------------
public interface StoreAM extends ApplicationModule {
    void loginInitialize();
}

